apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-nodejs.fullname" . }}-secret
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ required "A valid dbPassword is required via --set secret.dbPassword" .Values.secret.dbPassword | b64enc | quote }}