apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.secret.dbPassword | default "defaultSecret123!" | b64enc | quote }}